modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-or-later"
issueTrackerURL="https://github.com/KolbieCheese/WebhookIntegrations-BIB/issues"
[[mods]]
modId="webhookintegrations"
version="${version}"
displayName="WebhookIntegrations (Forge)"
authors="rudynakodach, Beauty in Blocks"
displayTest="IGNORE_SERVER_VERSION"
description='''Configurable Discord webhooks for Minecraft Forge servers. Based on WebhookIntegrations by rudynakodach.'''
[[dependencies.webhookintegrations]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="SERVER"
[[dependencies.webhookintegrations]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="SERVER"
